// Mapping of team names to their tracks, extracted from scripts/seed.ts
export const teamTrackMap: Record<string, string> = {
  Deepsick: "AI_ART_PREU",
  "AI Avengers": "AI_ART_PREU",
  "Bit Venom": "AI_ART_PREU",
  "Art Attack": "AI_ART_PREU",
  codeX: "AI_ART_PREU",
  "ai inventors": "AI_ART_PREU",
  "Mesti WIn": "AI_ART_PREU",
  "FIA Kuching": "AI_ART_PREU",
  KKTMByte: "AI_ART_PREU",
  Chatgpt: "AI_ART_PREU",
  NeuralCreators: "AI_ART_UPPERSEC",
  "Pixel Prophets": "AI_ART_UPPERSEC",
  "Deep Fried Neurons": "AI_ART_UPPERSEC",
  "The Art-Tificials": "AI_ART_UPPERSEC",
  "Algorithmic Artists": "AI_ART_UPPERSEC",
  PineApples: "AI_ART_UPPERSEC",
  Sapors: "AI_ART_UPPERSEC",
  "The Four Stars": "AI_ART_UPPERSEC",
  "Ctrl+S+Elite": "AI_ART_UPPERSEC",
  "Original Intelligence": "AI_ART_UPPERSEC",
  findU: "AI_INNOVATION_PREU",
  "When you can't C, so you Python": "AI_INNOVATION_PREU",
  LGG灵感菇: "AI_INNOVATION_PREU",
  "Skibidi Sigma": "AI_INNOVATION_PREU",
  "Seismo AI": "AI_INNOVATION_PREU",
  "Wi-fighters": "AI_INNOVATION_PREU",
  INNOLAB: "AI_INNOVATION_PREU",
  "Chaser Ginas": "AI_INNOVATION_PREU",
  "NEIVCE LWH 2": "AI_INNOVATION_PREU",
  "404 Name Not Found": "AI_INNOVATION_PREU",
  Eone: "AI_INNOVATION_UPPERSEC",
  AIvengers: "AI_INNOVATION_UPPERSEC",
  "Strategic Agents": "AI_INNOVATION_UPPERSEC",
  "Frog Dogs": "AI_INNOVATION_UPPERSEC",
  "Blue Jay²": "AI_INNOVATION_UPPERSEC",
  "Microsoft Support Group": "AI_INNOVATION_UPPERSEC",
  "All In For One": "AI_INNOVATION_UPPERSEC",
  "404 Brain Not Found": "AI_INNOVATION_UPPERSEC",
  "Ad Astra": "AI_INNOVATION_UPPERSEC",
  RedBean: "AI_INNOVATION_UPPERSEC",
  kthxbyte: "AI_TECHNICAL_PREU",
  Chincai: "AI_TECHNICAL_PREU",
  "Sunway ADTP innovators": "AI_TECHNICAL_PREU",
  "404": "AI_TECHNICAL_PREU",
  "Code Storm": "AI_TECHNICAL_PREU",
  VARS: "AI_TECHNICAL_PREU",
  CantByteUs: "AI_TECHNICAL_PREU",
  Earendel: "AI_TECHNICAL_PREU",
  "ZYLCH AI": "AI_TECHNICAL_PREU",
  "MONKIE BOI SKUAD": "AI_TECHNICAL_PREU",
  "The Voyagers": "AI_TECHNICAL_UPPERSEC",
  harm: "AI_TECHNICAL_UPPERSEC",
  Hollowlisme: "AI_TECHNICAL_UPPERSEC",
  brAIn: "AI_TECHNICAL_UPPERSEC",
  WhatsAI: "AI_TECHNICAL_UPPERSEC",
  Ouroboros: "AI_TECHNICAL_UPPERSEC",
  "The Future": "AI_TECHNICAL_UPPERSEC",
  "The Blues": "AI_TECHNICAL_UPPERSEC",
  Error404: "AI_TECHNICAL_UPPERSEC",
  AetherMind: "AI_TECHNICAL_UPPERSEC",
};

export const allTracks = [
  "AI_ART_PREU",
  "AI_ART_UPPERSEC",
  "AI_INNOVATION_PREU",
  "AI_INNOVATION_UPPERSEC",
  "AI_TECHNICAL_PREU",
  "AI_TECHNICAL_UPPERSEC",
];
